version: '2'

services:
  wordpress:
    build: wordpress
    restart: always
    depends_on:
      - wordpress_db
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: wordpress_db
      VIRTUAL_HOST: wordpress.untrobotics.com
      LETSENCRYPT_HOST: wordpress.untrobotics.com
      LETSENCRYPT_EMAIL: charlesbido.dev@gmail.com
      WORDPRESS_DEBUG: "1"
      WORDPRESS_CONFIG_EXTRA: define( 'AUTOMATIC_UPDATER_DISABLED', true );
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress/www/html:/var/www/html
      - ./wordpress/plugins:/usr/src/wordpress/wp-content/plugins
      - ./phpggc:/phpggc


  wordpress_db:
    image: mariadb:10.2
    restart: always
    volumes:
      - wordpress_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
volumes:
  wordpress_data: